name: CI

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          cache: true
      - name: Install dependencies
        run: |
          pdm install -d
      - name: Ruff linting
        run: |
          pdm run lint
        continue-on-error: true
      - name: Test with pytest
        run: |
          pdm run test
